### ISSUE TITLE
Salsa20 and Poly1305

### ISSUE THREAD

**Issue by cwharris** [ektrah/nsec#2]
I'm putting together a .NET Core Discord client, and the voice connection requires raw opus stream encoded using `xsalsa_poly1305`.

https://discordapp.com/developers/docs/topics/voice-connections

Not being a crypto guy myself, I am new to NaCl, libsodium, etc, and have stupid questions to ask:

1) what is `xsalsa_poly1305`?
2) can I utilize it using NSec?

😅

**Comment by ektrah** [comment]
XSalsa20+Poly1305 is a symmetric-key encryption algorithm. It provides authenticated encryption, similar to an AEAD algorithm. NSec currently does not provide an API for it, but I plan to add one once items with a higher priority on my to-do list are done (which includes making a pre-release of NSec).

**Comment by cwharris** [comment]
If there's anything I can do to help, please let me know. I haven't implemented encryption algorithms before, but I have 12 years of .NET experience. I can help out with build automation, testing, etc. Also, if there's an RFC spec for something, I could probably figure it out.

**Comment by cwharris** [comment]
If you need an extra hand with something, I'd be happy to help.

**Comment by cwharris** [comment]
@ektrah Hey, I see you're still working on NSec, which is pretty cool. I realize you haven't asked for help with the project (at least not here on Github), but it's something I'd like to use here pretty soon (v1 or pre-release - I'm flexible). Thing is, I want to use a particular algorithm (as mentioned previously). I'm a skilled developer and I'd like to implement said algorithm, but I don't know the first thing about encryption algorithms and I haven't been able to find a grip to latch on to, metaphorically speaking. Essentially, I have no idea where to start (I've looked. I really have).

If you provide me with enough information to *get started*, such as a book, website, reference implementation, documentation, etc, I'd be able to handle the development without any hand-holding. If it turns out you like the implementation and want to use it in NSec, great. If not, you will have helped a fellow engineer learn more about your neck of the woods, and for that I would be eternally grateful.

**Comment by ektrah** [comment]
NSec is very cutting-edge and uses C# features that still haven't been announced officially. It looks like they'll come with .NET Core 2.1/Visual Studio 15.5 release, though. I expect a big reveal at the upcoming *connect();* in November. It's pretty cool!

Until then, there is not really much to do. The actual crypto algorithms are already implemented; NSec relies on libsodium for this. What NSec does is provide fast, usable C# APIs. Most of these are in place already as well; only a few algorithms haven't been designed an API yet. This includes the `xsalsa20_poly1305` algorithm referenced by the Discord spec. I haven't decided yet how I want to expose it, since it doesn't seem to have caught on much compared to the standardized AES-GCM and ChaCha20-Poly1305 AEAD constructions.

If you're willing to experiment with the .NET Core 2.1 alpha bits and accept APIs breaking a bunch of times, I could cook something up quickly to get you started with the Discord spec. Ping me at contact@nsec.rocks.

**Comment by ektrah** [comment]
Added to NSec.Experimental in e3723cfa7d109809417d9f3b39aa01fe794c2354
