### ISSUE TITLE
Document usage regarding DLLs

### ISSUE THREAD

**Issue by ysangkok** [ektrah/nsec#23]
I am trying to debug NSec failing at runtime because it cannot find libsodium on Windows, using Visual Studio 2019.

I have downloaded from master, built a nupkg. I start a new C# project, make a custom package source with a directory containing this nupkg. Then I can install the nupkg into the repo if I check "Include prerelease".

After installing, the path attribute of the "NSec.Cryptography" item in the dependencies listing of the Solution Explorer is "C:\Users\janus\source\repos\ConsoleApp1\packages\NSec.Cryptography.19.10.0-preview1-28213-71\lib\netstandard2.0\NSec.Cryptography.dll".

When running the application with has a Main simply containing `NSec.Cryptography.AeadAlgorithm.ChaCha20Poly1305.Encrypt(null, new NSec.Cryptography.Nonce(), null, null);`, I get:

```

Unhandled Exception: System.PlatformNotSupportedException: Could not initialize platform-specific components. NSec may not be supported on this platform. See https://nsec.rocks/docs/install for more information. ---> System.DllNotFoundException: Unable to load DLL 'libsodium': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.Libsodium.sodium_library_version_major()
   at NSec.Cryptography.Sodium.InitializeCore()
   --- End of inner exception stack trace ---
   at NSec.Cryptography.Sodium.InitializeCore()
   at NSec.Cryptography.Sodium.Initialize()
   at NSec.Cryptography.Algorithm..ctor()
   at NSec.Cryptography.AeadAlgorithm..ctor(Int32 keySize, Int32 nonceSize, Int32 tagSize)
   at NSec.Cryptography.ChaCha20Poly1305..ctor()
   at NSec.Cryptography.AeadAlgorithm.get_ChaCha20Poly1305()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\janus\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```

Now, I see there is a libsodium package on Nuget, but I tried something else, I dunno if it makes sense: I downloaded msys2, installed `mingw-w64-i686-gcc` and `make` and I was able to build libsodium from source. So I copy `libsodium-23.dll` into the build directory with a simpler name:

    cp src/libsodium/.libs/libsodium-23.dll /c/Users/janus/source/repos/ConsoleApp1/ConsoleApp1/bin/Debug/libsodium.dll

And now I get:

```
Unhandled Exception: System.InvalidOperationException: An error occurred while initializing cryptographic primitives.
   at NSec.Cryptography.Sodium.InitializeCore()
   at NSec.Cryptography.Sodium.Initialize()
   at NSec.Cryptography.Algorithm..ctor()
   at NSec.Cryptography.AeadAlgorithm..ctor(Int32 keySize, Int32 nonceSize, Int32 tagSize)
   at NSec.Cryptography.ChaCha20Poly1305..ctor()
   at NSec.Cryptography.AeadAlgorithm.get_ChaCha20Poly1305()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\janus\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```

**Comment by ektrah** [comment]
It seems you’re trying to use the package in a .NET Framework project.

.NET Framework has limited support for NuGet packages with platform-specific libraries; have a look at https://nsec.rocks/docs/install for some hints, but running NSec on .NET Framework is essentially “at your own risk” and not recommended.

**Comment by knocte** [comment]
I understand the willingness to not support .NETFramework, but @ysangkok was only mentioning .NetStandard2.0 here. IMO compatibility with .NetStandard2.0 is important because it enables usage with Xamarin apps such as Xamarin.Android, Xamarin.iOS, etc. Converting most projects from .NETCore 2.x to .NetStandard2.0 has been, IME, very easy.

**Comment by ektrah** [comment]
The issue is that NSec uses two sets of APIs: the .NET ones (and there it conforms to .NET Standard 2.0) and the libsodium ones (which is completely unrelated to .NET).

Using the libsodium APIs requires two things: that a pre-compiled binary is available for the specific platform and that this pre-compiled binary can be picked up by the .NET runtime from a NuGet package.

The current situation is that pre-compiled binaries are not available everywhere where .NET Standard is available and that runtimes other than .NET Core have trouble picking up the pre-compiled binaries from the NuGet package.

It's a bit unfortunate that the NSec NuGet package can only advertise its .NET requirements, while the libsodium requirements can only be checked at runtime after it has been successfully added to the project...
