### ISSUE TITLE
Ed25519 to Curve25519

### ISSUE THREAD

**Issue by hitchhiker** [ektrah/nsec#26]
My apologies if I missed it somewhere -> is this currently implemented? 
https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519

**Comment by ektrah** [comment]
This API is currently not exposed, because the value is a bit unclear. It's not a good practice to use the same key for different purposes; if you're generating two keys anyway, why not generate them on the right curve directly?

**Comment by ektrah** [comment]
I'm closing this issue for now. Feel free to re-open.

**Comment by maurictg** [comment]
I would find it a useful feature. Consider the following scenario:

- Alice wants to send an encrypted message to Bob
- Bob already owns the public key of Alice, used to sign messages (Ed25519)
- Alice and Bob do not want another, redundant key exchange over the network

To send an encrypted message without another key exchange Alice and Bob just have to convert their keys into the X25519 scheme and do an ECDH  key-exchange locally to generate a new shared secret. From this shared secret an encryption key can be derived (with a salt which will be sent together with the message) that can be used to encrypt the message.

This might be useful because they just need one public key for both signing and encryption.

N.B. I saw this feature [is implemented](https://github.com/ektrah/nsec/blob/master/src/Experimental/KeyConverter.cs) to the Experimental folder. I was wondering when/if it will be added to the library and if not, if it is possible to publish another library with these "extra" features?
