### ISSUE TITLE
"Classic" public key encryption?

### ISSUE THREAD

**Issue by vegardlarsen** [ektrah/nsec#36]
Thank you for providing this library. It has been quite helpful in trying to get up to speed on cryptography.

I have a specific situation where I have a server that generates a large amount of data over time, and it should encrypt that data for a consumer to decrypt at a later point in time. Using this library, I have worked out (and got a demo working) that we should use a `KeyAgreementAlgorithm` and a `KeyDerivationAlgorithm` to agree to a shared encryption key (that can be salted).

This does however leave the encrypting party able to decrypt the data after it has been encrypted. I was hoping to avoid that.

I seem to recall that RSA (I may be wrong here) allowed you to encrypt short messages using the other party's public key, and that would come in helpful here. My plan of attack was initially:

1. The generator creates a random (or at least non-derivable at a later stage) symmetric key.
2. The generator encrypts the symmetric key using the consumer's public key.
3. The generator encrypts the data using the symmetric key.
4. The generator publishes both values.

At that point (and assuming that you can trust the generator, which is a discussion to be had on its own), only the consumer will be able to decrypt the data, because he is the only one with access to the private key to decrypt the symmetric key.

So the TL;DR: does NSec support (or intend to support) public-key encryption?

**Comment by ektrah** [comment]
At this moment, NSec does not include public-key authenticated encryption and there aren't any immediate plans to add such.

The primitives in NSec should be suitable for implementing public-key authenticated encryption, e.g., using a combination of `KeyAgreementAlgorithm`, `KeyDerivationAlgorithm`, and `AeadAlgorithm`. Getting that combination right is quite hard, though. In particular, `KeyDerivationAlgorithm` has a number of non-obvious considerations to be used correctly. So, I would recommend against any attempt at building such a combination oneself. The best solution would be to implement an existing standard with a reviewed specification. 

Libsodium, the library underlying NSec, provides some kind of public-key authenticated encryption ([docs](https://doc.libsodium.org/public-key_cryptography/authenticated_encryption)). This might do what you want. I haven't found a standard with a reviewed specification for that, however, which is why it's not exposed in NSec.

**Comment by vegardlarsen** [comment]
Thank you for your response. It reads as really good advice. I've read the libsodium docs you reference, and tried to read up on public key authenticated encryption, but there does not appear to be any standards that can be used, as you say.

In my case, I'll proceed with my proof of concept (meaning that the cryptography in this case is secondary to testing if the actual concept works) as I outlined above, using the ill-advised combination of `KeyAgreementAlgorithm`, `KeyDerivationAlgorithm` and `AeadAlgorithm`, the only problem for my use case is that the sender can decode the messages at a later stage.

Thank you for your feedback. :)
