### ISSUE TITLE
Merge pull request 32 into NSec.Experimental (ed25519 to x25519 conversion)

### ISSUE THREAD

**Issue by sigaloid** [ektrah/nsec#47]
I would appreciate if the code in https://github.com/ektrah/nsec/pull/32/files was merged even if it were in the experimental package and had an extra warning attached. Is there any issues with adding this? I can submit a pull request in a medium amount of time if there are no problems.

In issues/26 you say "if you're generating two keys anyway, why not generate them on the right curve directly?".

AFAIK however, you can generate a single ed25519 keypair, convert the private ed25519 key to a private x25519 key, and the x25519 public key corresponding to the private key can be converted with the ed25519 public key. That's the only way I can make sense of it otherwise projects that use "EdX25519 keys" would make no sense. (https://keys.pub/docs/specs/keys.html#edx25519) (https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519)  

This means exchanging a single signature key lets anyone convert the public ed25519 key into a public x25519 key that would correspond to the private x25519 key that would be formed by converting the private ed25519 key to x25519. Unless I have a fundamental misunderstanding of libsodium, of course. :man_shrugging:

**Comment by ektrah** [comment]
Adding the functions to NSec.Experimental is certainly possible. I would prefer if the parameters were `Key`/`PublicKey` instances instead of byte arrays, but otherwise the pull request looks good to me and would be welcome in NSec.Experimental.

Adding them to NSec itself is a bit different, because for that I'd like to understand the security implications better first.

Let's say you generate an Ed25519 key pair for signatures and then do the conversion to X25519 for key agreement:

```csharp
using var privateSignatureKey = Key.Create(SignatureAlgorithm.Ed25519);
var publicSignatureKey = privateSignatureKey.PublicKey;

using var privateKeyAgreementKey = ...Convert...(privateSignatureKey);
var publicKeyAgreementKey = ...Convert...(publicSignatureKey);
```

So, it's essentially the same key pair, but once in a form suitable for signatures and once in a form suitable for key agreement.

This is the crux: Generally, it's not recommended to use the same key for different purposes. The reason for that is that there can subtle interactions between those different purposes that weaken the individual security.

So, generally you would generate two separate key pairs and then could convert one of them:

```csharp
using var privateSignatureKey1 = Key.Create(SignatureAlgorithm.Ed25519);
var publicSignatureKey1 = privateSignatureKey.PublicKey;

using var privateSignatureKey2 = Key.Create(SignatureAlgorithm.Ed25519);
var publicSignatureKey2 = privateSignatureKey.PublicKey;

using var privateKeyAgreementKey = ...Convert...(privateSignatureKey2);
var publicKeyAgreementKey = ...Convert...(publicSignatureKey2);
```

But that IMHO doesn't really provide an advantage over generating an X25519 key pair directly:

```csharp
using var privateSignatureKey = Key.Create(SignatureAlgorithm.Ed25519);
var publicSignatureKey = privateSignatureKey.PublicKey;

using var privateKeyAgreementKey = Key.Create(KeyAgreementAlgorithm.X25519);
var publicKeyAgreementKey = privateKeyAgreementAlgorithmKey.PublicKey;
```

However, "generally" doesn't mean that it's completely impossible. In the specific case of Ed25519 and X25519, it could be fine. Or it could be fine if certain, specific rules are followed. That's what I'd like to understand better.

**Comment by sigaloid** [comment]
True, if you're going to have 2 keys, no point in converting at all. But if having a single key for both signing and encryption can be insecure (which is exactly what signal protocol does, they call it XEd25519), why does the signal protocol do it? I'm not questioning you, because you are correct that it can cause issues, but why does a massively used and "considered secure" protocol use it? Keys aren't even exchanged by users, so I can't even think of a reason why it's necessary. If it provides less security, why not use 2 keys on the backend?

**Comment by ektrah** [comment]
The designers of Signal may be aware of the "if certain, specific rules are followed" part. 😃

**Comment by sigaloid** [comment]
Is there anything specific to be aware of? Other than it may introduce specific security issues?

**Comment by sigaloid** [comment]
Actually, signal uses an X25519 key for EdDSA, not an Ed25519 key for ECDH (https://blog.filippo.io/using-ed25519-keys-for-encryption/#:~:text=It%20should%20be%20mentioned).

**Comment by ektrah** [comment]
I think the potential security issues are the critical part.

The blog post you've linked actually reinforces my point by saying that "it's pretty easy to use an Ed25519 public key for X25519", but that it also "remains open for future work is checking for cross-protocol attacks."

**Comment by sigaloid** [comment]
Thanks.
