### ISSUE TITLE
Full .NET framework build?

### ISSUE THREAD

**Issue by dustinsoftware** [ektrah/nsec#6]
Since .NET 4.6.1 is compatible with .NET Standard 2.0, would it be possible to support running on the full .NET framework? I can investigate adding support for this if you'd merge it in,

**Comment by ektrah** [comment]
NSec currently requires just .NET Standard 1.1, so in theory it's fully capable of running on most recent .NET Framework versions. In practice, .NET Framework is lacking compared to .NET Core when it comes to locating native libraries in NuGet packages: You can add the NSec.Cryptography package to a .NET Framework project, but will get a DllNotFoundException at runtime.

There are some project configurations in which it works; see the discussion in https://github.com/jedisct1/libsodium/pull/582. Alternatively, you can manually copy *libsodium.dll* to a location where .NET Framework can find it. It feels very inconvenient, though, which is why I'm currently advertising NSec for .NET Core only. I hope this will improve in future .NET Framework versions.

For now, I would very much welcome a pull requests that documents the conditions under which it reliably works out of the box. I don't think I want to merge any build scripts or other workarounds; I'd rather not advertise .NET Framework support at all than ship a package that requires troubleshooting after some installations.

**Comment by dustinsoftware** [comment]
Thanks for the reply. I have tested that manually copying the libsodium DLL allows the library to run in a full ASP.NET app without any issues.

I think an approach like [this](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/74375f6abd7c3701945e3a568dfe89ba2bb43f5c/NuGet/JavaScriptEngineSwitcher.ChakraCore.Native.win-x64/build/JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.props) would work fine. The consuming app would just need to add an `<Import Project ... />` element to the project file, which could be done automatically when the package is installed. We currently use that library in one of our production apps, and haven't had any trouble with copying the native library around.

**Comment by ektrah** [comment]
libsodium-net has an endless history of trouble with that approach; see many of the [open issues](https://github.com/adamcaudill/libsodium-net/issues). I'm not going to open up that can of worms.

Could you try this? https://github.com/ektrah/nsec/commit/f3e1f6aa46d6e30339a6c1cc7db7672d4871a15b
I've had success with this (without copying anything) in a .NET Framework 4.7.1 console application, but haven't tried it in other project types yet.
