### ISSUE TITLE
KDF: Difference between adding context in sharedsecret vs info?

### ISSUE THREAD

**Issue by abergs** [ektrah/nsec#60]
Hello,

I'm wondering if there are any practical differences if I encode "context" into the shared secret vs adding it in the info?

Alt 1: 
```csharp
var passphrase = "my-secret" + username;
var secret = SharedSecret.Import(Encoding.UTF8.GetBytes(passphrase));
var key = KeyDerivationAlgorithm.HkdfSha256.DeriveKey(secret, null, null, MacAlgorithm.HmacSha256)
```

Alt2
```csharp
var passphrase = "my-secret";
var info = Encoding.UTF8.GetBytes(username);
var secret = SharedSecret.Import(Encoding.UTF8.GetBytes(passphrase));
var key = KeyDerivationAlgorithm.HkdfSha256.DeriveKey(secret, null, info, MacAlgorithm.HmacSha256)
```

While using this library, I missed some practical guides. Would you like to receive contributions with "scenario" guides, e.g. "Using NSEC to HMAC your data and then verifying it"?

**Comment by ektrah** [comment]
Hejsan!

Regarding HKDF inputs, check out [RFC 5869](https://datatracker.ietf.org/doc/html/rfc5869) and the referenced [paper](http://eprint.iacr.org/2010/264). In practice, the protocol you're implementing should tell you exactly what inputs should go where. This is difficult to get right, so I would recommend against inventing your own scheme. Also note that HKDF requires cryptographically strong input keying material; a password is not suitable (use Argon2 or scrypt instead).

Some practical guides would be really nice to have. I think simple API usage examples could go right into the reference docs (like [here](https://nsec.rocks/docs/api/nsec.cryptography.incrementalmac#example)). Some more substantial "how-to"'s (like how to properly work with keys in NSec, how to properly use HKDF, etc.) would be awesome and could get their own pages. I'm quite nit-picky when it comes to guides to cryptography, though, which is why I never managed to finish writing any for NSec. So contributions would be very welcome 😺

**Comment by abergs** [comment]
@ektrah Hej! Så trevligt att möte en granne. 

Thanks for the detailed reply.
I'm working my way through the PDF. Not being "fluent" in cryptography, I must admit some concepts are not easy to grasp.

The "passphrase" in my question above is however a simplification. My idea was to use a static random value (e.g uuid/long random string/ 32 random bytes) and then supply a "userId" to make sure the key source is different for each user.

From reading the PDF, I'm still not sure if a static (seldom rotated) source of 32 random bits is considered a safe source.

Supplying the UserId as salt would not be enough from that I can understand (value can be known but must be random) - but a sha256(userId) would be a suitable salt. 


The derived key would be used to HMAC shortlived API payloads.

If your open to discussing this more I'd be happy to share some more code and then make sure to write up something so that others can learn from my mistakes 🙂
