### ISSUE TITLE
WebAssembly Support

### ISSUE THREAD

**Issue by caleblloyd** [ektrah/nsec#64]
[WebAssembly native dependencies](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0) are supported as of .NET 6 - [talk demonstrating the capability](https://www.youtube.com/watch?v=kesUNeBZ1Os)

It would be great if `nsec` could link libsodium in WebAssembly so that the package would work in Blazor!

**Comment by Jack-Edwards** [comment]
Seconded.  I added an issue on the main libsodium repo asking if their nuget package could contain a binary for webassembly, which should be possible now.  To be honest I'm struggling to follow along with the docs that cover this stuff.  Not even sure if asking on the libsodium repo is the right way to go.

https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0

**Comment by caleblloyd** [comment]
I spent a few hours trying to get this to work to no avail.  Microsoft's documentation seems to indicate it is possible, but I could not figure out the part where `wasm-tools` to compiles `libsodium`

**Comment by Jack-Edwards** [comment]
I made some progress in another .NET wrapper/repo.

https://github.com/ektrah/libsodium-core/issues/87
https://github.com/ektrah/libsodium-core/pull/88

**Comment by NKnusperer** [comment]
Any update regarding this topic?
An official Webassembly version already exist via [jedisct1/libsodium.js](https://github.com/jedisct1/libsodium.js/)

**Comment by Heteroculturalism** [comment]
I would love to see this as well.  I'm trying to build a Stellar wallet as a Blazor PWA.

**Comment by Jack-Edwards** [comment]
I'm beginning to work on a nuget package that will provide libsodium capabilities for Blazor WASM.  https://github.com/Jack-Edwards/BlazorSodium/tree/PasswordHash.Argon

I specifically linked the `PasswordHash.Argon` branch since that branch is the cleanest and hasn't been linked to other repos, where I still have some outstanding issues and questions.

Example usage:

```
@code {
   [Inject]
   IBlazorSodiumService BlazorSodiumService { get; set; }

   protected override void OnInitialized()
   {
      byte[] saltBytes = BlazorSodiumService.PasswordHash.ArgonGenerateSalt();
      Console.WriteLine(saltBytes.Length);
   }
}
```

I'd appreciate some community feedback on what the interfaces should look like and which libsodium API's are the most critically needed.  Or just feel free to copy what I'm doing and make a competing library.

Note, it's not possible to simply link the libsodium wasm32-wasi module to our Blazor WASM projects as if it were a native file reference.  The wasm32-wasi module requires a WASI runtime, which is not currently available in the browser or offered by .NET.  The route I'm taking actually uses libsodium.js and JSInterop.

**Comment by Jack-Edwards** [comment]
The project I'm working to support Blazor WASM is available as a nuget package, now.

https://www.nuget.org/packages/BlazorSodium

Version 0.1.1-alpha supports:
- RandomBytes
- StreamCipher - ChaCha20
- StreamCipher - XChaCha20

There are many functions remaining to add support for: https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols

I intend to add support for everything, but it will take some time.  Please reach out with any feedback.

**Comment by Jack-Edwards** [comment]
Hey folks.  BlazorSodium now has feature parity with the version of libsodium.js available on NPM.  Feel free to check it out, leave feedback, or incorporate the same methods into updating nsec.  I'd actually love to use nsec in the browser myself.

**Comment by ektrah** [comment]
It seems there is no straight forward way to add WebAssembly support to NSec due to the dependency on libsodium. BlazorSodium  looks quite promising, so I hope that this can fill the gap for now.

I'll close this issue, though I'd be happy to add WebAssembly support to NSec if someone manages to get it to work (e.g., using a future .NET version).
