### ISSUE TITLE
Private Key

### ISSUE THREAD

**Issue by dolphinsd** [ektrah/nsec#9]
Once the key generated, how do I get private key to store it?!

**Comment by ektrah** [comment]
If you want to store a private key in a file, you can use the [`key.Export` method](https://nsec.rocks/docs/api/nsec.cryptography.key#export-keyblobformat) as follows:

```csharp
var algorithm = SignatureAlgorithm.Ed25519;

var creationParameters = new KeyCreationParameters
{
    ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving
};

// create a new key
using (var key = new Key(algorithm, creationParameters))
{
    // export it
    var blob = key.Export(KeyBlobFormat.NSecPrivateKey);

    File.WriteAllBytes("myprivatekey.nsec", blob);
}
```
Later, you can re-import the key using the [`Key.Import` method](https://nsec.rocks/docs/api/nsec.cryptography.key#import-algorithm-readonlyspan-byte-keyblobformat-in-keycreationparameters) as follows:

```csharp
var algorithm = SignatureAlgorithm.Ed25519;

var blob = File.ReadAllBytes("myprivatekey.nsec");

using (var key = Key.Import(algorithm, blob, KeyBlobFormat.NSecPrivateKey))
{
    algorithm.Sign(key, ...);
}
```

The `format` parameter specifies the [format to use](https://nsec.rocks/docs/api/nsec.cryptography.keyblobformat) when exporting the private key. Currently, the formats `NSecPrivateKey`, `PkixPrivateKey`, and `RawPrivateKey` are available. Note that all of them export the private key in plaintext without any protections, which is why the original key needs to be generated with the [`AllowPlaintextArchiving` flag](https://nsec.rocks/docs/api/nsec.cryptography.keyexportpolicies).

Does that answer your question?
